import { TriviaTopic } from '@/types'

type TopicList = { [key in TriviaTopic]: string[] }

export const topicList: TopicList = {
	Art: [
		'Music',
		'Painting',
		'Movies',
		'Art History',
		'Literature',
		'Drawing',
		'Sculpture',
		'Photography',
		'Painting Artists',
		'Classical Music',
		'Musical Instruments',
		'Movie Directors',
		'Writers',
	],
	Entertainment: [
		'Memes ',
		'Sports',
		'Social Media',
		'Celebrities',
		'TV Shows',
		'Cartoons',
		'Anime',
		'Video Games',
		'Comedy',
		'Youtubers',
		'Pop Culture',
		'Comics',
		'Manga',
		'The biggest companies in the world',
		'The internet',
	],
	Geography: [
		'Countries',
		'Continents',
		'Cities',
		'The weather',
		'Oceans',
		'Popular world places',
		'Forests',
		'Volcanos',
		'Jungles',
		'Deserts',
		'Rivers',
		'Mountains',
		'Islands',
		'Lakes',
	],
	History: [
		'Politics',
		'Ancient Civilizations',
		'War',
		'Religions',
		'Monuments',
		'Ancient Egypt',
		'World War I',
		'World War II',
		'Renaissance',
		'American revolution',
		'Industrial Revolution',
		'French Revolution',
		'Cold war',
		'American presidents',
		'Ancient Greece',
		'Roman Empire',
		'Persian Empire',
		'Presidents',
		'Philosophy',
	],
	Science: [
		'Space',
		'Math',
		'Animals',
		'Plants',
		'Humans',
		'Medicine',
		'Technology',
		'Dinosaurs',
		'Astronomy',
		'Genetics',
		'Popular scientists',
		'Human anatomy',
		'Illnesses',
		'Computers',
		'Artificial intelligence',
		'Biology',
		'The cosmos',
		'Earth',
	],
}
