export const humanRoles = [
	'Mother',
	'Father',
	'Sister',
	'Brother',
	'Grandmother',
	'Grandfather',
	'Daughter',
	'Son',
	'Aunt',
	'Uncle',
	'Niece',
	'Nephew',
	'Cousin',
	'Teacher',
	'Math teacher',
	'PE teacher',
	'Philosophy teacher',
	'Doctor',
	'Nurse',
	'Engineer',
	'Lawyer',
	'Police officer',
	'Firefighter',
	'Waiter',
	'Waitress',
	'Artist',
	'Musician',
	'Writer',
	'Actor',
	'Actress',
	'Dancer',
	'Athlete',
	'Scientist',
	'Astronaut',
	'Pilot',
	'Architect',
	'Carpenter',
	'Plumber',
	'Electrician',
	'Mechanic',
	'Farmer',
	'Gardener',
	'Librarian',
	'Professor',
	'Student',
	'CEO',
	'Entrepreneur',
	'Accountant',
	'Financial advisor',
	'Salesperson',
	'Marketing manager',
	'Journalist',
	'Photographer',
	'Chef',
	'Baker',
	'Barista',
	'Hairstylist',
	'Makeup artist',
	'Fashion designer',
	'Model',
	'Retail worker',
	'Customer service representative',
	'IT specialist',
	'Programmer',
	'Web developer',
	'Graphic designer',
	'Product manager',
	'Project manager',
	'Social media manager',
	'Event planner',
	'Wedding planner',
	'Real estate agent',
	'Architectural designer',
	'Civil engineer',
	'Environmentalist',
	'Biologist',
	'Chemist',
	'Law enforcement officer',
	'Paramedic',
	'Psychologist',
	'Therapist',
	'Social worker',
	'Veterinarian',
	'Marine biologist',
	'Zoologist',
	'Geologist',
	'Paleontologist',
	'Researcher',
	'Lecturer',
	'Principal',
	'Guidance counselor',
	'Speech therapist',
	'Physical therapist',
	'Occupational therapist',
	'Pharmacist',
	'Dentist',
	'Orthodontist',
	'Surgeon',
	'Anesthesiologist',
	'Optometrist',
	'Ophthalmologist',
	'Physician assistant',
	'Bus driver',
	'Taxi driver',
	'Train conductor',
	'News anchor',
	'Meteorologist',
	'Financial analyst',
	'Stockbroker',
	'Archaeologist',
	'Anthropologist',
	'Translator',
	'Interpreter',
	'Foreign correspondent',
	'Film director',
	'Film producer',
	'Screenwriter',
	'Video editor',
	'Sound engineer',
	'Special effects artist',
	'Stunt performer',
	'Casting director',
	'Tour guide',
	'Travel agent',
	'Hotel manager',
	'Flight attendant',
	'Cruise ship captain',
	'Professional gamer',
	'Ethical hacker',
	'Robotics engineer',
	'Environmental engineer',
	'Solar energy technician',
	'Wind turbine technician',
	'Welder',
	'Blacksmith',
	'Astrologer',
	'Magician',
	'Tattoo artist',
	'Fitness instructor',
	'Yoga instructor',
	'Life coach',
	'Motivational speaker',
]
